services:
  localstack:
    image: localstack/localstack:stable
    ports:
      - '4566:4566'
    environment:
      - SERVICES=dynamodb,sqs,sns,lambda,ssm,secretsmanager,logs,iam,events,s3,apigateway
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:-}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/_localstack/health']
      interval: 5s
      timeout: 5s
      retries: 10
