import * as fs from 'fs';
import * as path from 'path';
import chalk from 'chalk';
import ora from 'ora';
import { loadConfig, formatError, writeCache, readCache, setCacheDir } from '../../core/index.js';
import { extractDynamoMetadata } from '../../adapters/aws/dynamodb.js';
import { extractPostgresMetadata } from '../../adapters/db/postgres.js';
import { extractMySQLMetadata } from '../../adapters/db/mysql.js';
import { extractMongoMetadata } from '../../adapters/db/mongodb.js';
import { extractIaCSchema, type IaCLambda, type IaCOutput } from '../../adapters/iac/terraform.js';
import {
  extractSQSMetadata,
  extractSNSMetadata,
  extractSSMMetadata,
  extractSecretsMetadata,
  extractLambdaMetadata,
  extractEventBridgeMetadata,
  extractRDSMetadata,
  extractAPIGatewayMetadata,
  extractCognitoMetadata,
} from '../../adapters/aws/services.js';
import { extractLogsMetadata } from '../../adapters/aws/logs.js';
import { extractS3Metadata } from '../../adapters/aws/s3.js';
import { scanRepository } from '../../context/index.js';
import { buildGraph, addStackOutputNodes } from '../../graph/index.js';
import {
  runAllAnalyzers,
  IaCDriftAnalyzer,
  PipelineAnalyzer,
  FullTableScanAnalyzer,
  MissingGSIAnalyzer,
  HotPartitionAnalyzer,
  MissingIndexAnalyzer,
  NplusOneAnalyzer,
  LargeSelectAnalyzer,
  MissingMySQLIndexAnalyzer,
  MySQLFullTableScanAnalyzer,
  MissingMongoIndexAnalyzer,
  MongoCollectionScanAnalyzer,
  MissingDLQAnalyzer,
  UnencryptedQueueAnalyzer,
  LargeQueueBacklogAnalyzer,
  VisibilityTimeoutMismatchAnalyzer,
  MissingSecretRotationAnalyzer,
  MissingLogRetentionAnalyzer,
  LambdaDefaultMemoryAnalyzer,
  LambdaHighTimeoutAnalyzer,
  LambdaMissingTriggerDLQAnalyzer,
  LambdaMissingIAMPermissionsAnalyzer,
  RDSPubliclyAccessibleAnalyzer,
  RDSNoBackupAnalyzer,
  RDSUnencryptedAnalyzer,
  RDSNoDeletionProtectionAnalyzer,
  RDSNoMultiAZAnalyzer,
  S3PublicAccessAnalyzer,
  S3MissingVersioningAnalyzer,
  S3UnencryptedAnalyzer,
} from '../../analyzers/index.js';
import { printFinding, printSummaryBox, log, printHeader } from '../utils.js';
import type {
  Analyzer,
  Finding,
  ServicesMeta,
  ExtractedOperation,
  InfrawiseConfig,
  DynamoTableMetadata,
  PostgresTableMetadata,
  MySQLTableMetadata,
  MongoCollectionMetadata,
} from '../../types.js';

interface CachedMeta {
  dynamoMeta: DynamoTableMetadata[];
  postgresMeta: PostgresTableMetadata[];
  mysqlMeta: MySQLTableMetadata[];
  mongoMeta: MongoCollectionMetadata[];
  servicesMeta: ServicesMeta;
}

interface AnalyzeOptions {
  config?: string;
  repo?: string;
  noCache?: boolean;
  output?: string;
  severity?: 'high' | 'medium' | 'low';
  silent?: boolean;
}

const SEVERITY_ORDER: Record<string, number> = { high: 3, medium: 2, low: 1, verify: 0 };

function buildMarkdownReport(findings: Finding[], projectName: string): string {
  const date = new Date().toISOString().split('T')[0];
  const high = findings.filter((f) => f.severity === 'high');
  const medium = findings.filter((f) => f.severity === 'medium');
  const low = findings.filter((f) => f.severity === 'low');
  const verify = findings.filter((f) => f.severity === 'verify');

  const renderGroup = (label: string, emoji: string, group: Finding[]) => {
    if (group.length === 0) return '';
    const rows = group.map((f) => `| ${f.issue} | ${f.recommendation} |`).join('\n');
    return `\n## ${emoji} ${label} (${group.length})\n\n| Issue | Recommendation |\n|---|---|\n${rows}\n`;
  };

  return [
    `# infrawise report — ${projectName}`,
    `_Generated: ${date}_`,
    '',
    `**${findings.length} finding(s)**: ${high.length} high · ${medium.length} medium · ${low.length} low · ${verify.length} verify`,
    renderGroup('High severity', '🔴', high),
    renderGroup('Medium severity', '🟡', medium),
    renderGroup('Low severity', '🟢', low),
    renderGroup('Verify (check intent)', '🔵', verify),
    '',
    '_Generated by [infrawise](https://github.com/Sidd27/infrawise) — MCP server for AWS infrastructure analysis_',
  ]
    .filter((l) => l !== undefined)
    .join('\n');
}

function mkSpinner(text: string) {
  return ora({ text: chalk.dim(text), color: 'cyan' }).start();
}

// Runs one extractor behind a spinner: succeeds with a count summary, or warns and
// returns undefined on failure so a single service never aborts the whole analysis.
async function extract<T>(
  enabled: boolean | undefined,
  spinnerText: string,
  label: string,
  fn: () => Promise<T>,
  summarize: (result: T) => string,
): Promise<T | undefined> {
  if (!enabled) return undefined;
  const s = mkSpinner(spinnerText);
  try {
    const result = await fn();
    s.succeed(chalk.green(label) + chalk.dim(`  ${summarize(result)}`));
    return result;
  } catch (err) {
    s.warn(
      chalk.yellow(`${label} skipped`) +
        chalk.dim(`  ${err instanceof Error ? err.message : String(err)}`),
    );
    return undefined;
  }
}

// Single source of truth for which analyzers run given the config. Used by both the
// full `runAnalyze` and the cache-backed `runCodeRefresh` so the two never drift.
function buildAnalyzers(
  config: InfrawiseConfig,
  iacDriftAnalyzer: IaCDriftAnalyzer | undefined,
  iacLambdas: IaCLambda[],
): Analyzer[] {
  const pipelineAnalyzer = new PipelineAnalyzer();
  pipelineAnalyzer.setIaCLambdas(iacLambdas);
  return [
    ...(config.dynamodb?.enabled === true
      ? [
          new FullTableScanAnalyzer(),
          new MissingGSIAnalyzer(),
          new HotPartitionAnalyzer(
            config.analysis?.hotPartitionThreshold,
            config.analysis?.hotPartitionThresholds,
          ),
        ]
      : []),
    ...(config.postgres?.enabled
      ? [new MissingIndexAnalyzer(), new NplusOneAnalyzer(), new LargeSelectAnalyzer()]
      : []),
    ...(config.mysql?.enabled
      ? [new MissingMySQLIndexAnalyzer(), new MySQLFullTableScanAnalyzer()]
      : []),
    ...(config.mongodb?.enabled
      ? [new MissingMongoIndexAnalyzer(), new MongoCollectionScanAnalyzer()]
      : []),
    ...(config.sqs?.enabled === true
      ? [
          new MissingDLQAnalyzer(),
          new UnencryptedQueueAnalyzer(),
          new LargeQueueBacklogAnalyzer(),
          new VisibilityTimeoutMismatchAnalyzer(),
        ]
      : []),
    ...(config.secretsManager?.enabled === true ? [new MissingSecretRotationAnalyzer()] : []),
    ...(config.cloudwatchLogs?.enabled ? [new MissingLogRetentionAnalyzer()] : []),
    ...(config.lambda?.enabled === true
      ? [
          new LambdaDefaultMemoryAnalyzer(),
          new LambdaHighTimeoutAnalyzer(),
          new LambdaMissingTriggerDLQAnalyzer(),
          new LambdaMissingIAMPermissionsAnalyzer(),
        ]
      : []),
    ...(config.rds?.enabled === true
      ? [
          new RDSPubliclyAccessibleAnalyzer(),
          new RDSNoBackupAnalyzer(),
          new RDSUnencryptedAnalyzer(),
          new RDSNoDeletionProtectionAnalyzer(),
          new RDSNoMultiAZAnalyzer(),
        ]
      : []),
    ...(config.s3?.enabled === true
      ? [
          new S3PublicAccessAnalyzer(),
          new S3MissingVersioningAnalyzer(),
          new S3UnencryptedAnalyzer(),
        ]
      : []),
    ...(iacDriftAnalyzer ? [iacDriftAnalyzer] : []),
    pipelineAnalyzer,
  ];
}

export async function runAnalyze(options: AnalyzeOptions = {}): Promise<void> {
  printHeader('Running Analysis');

  let config;
  try {
    config = loadConfig(options.config);
    setCacheDir(path.dirname(path.resolve(options.config ?? 'infrawise.yaml')));
    log.success('Config loaded', options.config ?? 'infrawise.yaml');
  } catch (err) {
    console.error(formatError(err));
    process.exit(1);
  }

  const repoPath = options.repo ?? process.cwd();
  const minSeverity = options.severity ? (SEVERITY_ORDER[options.severity] ?? 1) : 0;
  const awsCfg = {
    region: config.aws?.region,
    profile: config.aws?.profile,
  };

  const servicesMeta: ServicesMeta = {};

  const dynamoMeta =
    (await extract(
      config.dynamodb?.enabled === true,
      'Extracting DynamoDB tables...',
      'DynamoDB',
      () => extractDynamoMetadata(config),
      (r) => `${r.length} table(s)`,
    )) ?? [];

  const pgConn = config.postgres?.enabled ? config.postgres.connectionString : undefined;
  const postgresMeta =
    (await extract(
      !!pgConn,
      'Extracting PostgreSQL schema...',
      'PostgreSQL',
      () => extractPostgresMetadata(pgConn ?? ''),
      (r) => `${r.length} table(s)`,
    )) ?? [];

  const mysqlConn = config.mysql?.enabled ? config.mysql.connectionString : undefined;
  const mysqlMeta =
    (await extract(
      !!mysqlConn,
      'Extracting MySQL schema...',
      'MySQL',
      () => extractMySQLMetadata(mysqlConn ?? ''),
      (r) => `${r.length} table(s)`,
    )) ?? [];

  const mongoConn = config.mongodb?.enabled ? config.mongodb.connectionString : undefined;
  const mongoMeta =
    (await extract(
      !!mongoConn,
      'Extracting MongoDB schema...',
      'MongoDB',
      () => extractMongoMetadata(mongoConn ?? '', config.mongodb?.databases),
      (r) => `${r.length} collection(s)`,
    )) ?? [];

  servicesMeta.sqs = await extract(
    config.sqs?.enabled === true,
    'Extracting SQS queues...',
    'SQS',
    () => extractSQSMetadata(awsCfg),
    (r) => `${r.length} queue(s)`,
  );

  servicesMeta.sns = await extract(
    config.sns?.enabled === true,
    'Extracting SNS topics...',
    'SNS',
    () => extractSNSMetadata(awsCfg),
    (r) => `${r.length} topic(s)`,
  );

  servicesMeta.ssm = await extract(
    config.ssm?.enabled === true,
    'Extracting SSM parameters...',
    'SSM',
    () => extractSSMMetadata({ ...awsCfg, paths: config.ssm?.paths }),
    (r) => `${r.length} parameter(s)  (metadata only, no values)`,
  );

  servicesMeta.secrets = await extract(
    config.secretsManager?.enabled === true,
    'Extracting Secrets Manager metadata...',
    'Secrets Manager',
    () => extractSecretsMetadata(awsCfg),
    (r) => `${r.length} secret(s)  (names/rotation only, no values)`,
  );

  servicesMeta.lambda = await extract(
    config.lambda?.enabled === true,
    'Extracting Lambda functions...',
    'Lambda',
    () => extractLambdaMetadata(awsCfg, config.lambda?.includeFunctions),
    (r) => `${r.length} function(s)`,
  );

  servicesMeta.eventbridge = await extract(
    config.eventbridge?.enabled === true,
    'Extracting EventBridge rules...',
    'EventBridge',
    () => extractEventBridgeMetadata(awsCfg),
    (r) => `${r.length} rule(s)`,
  );

  servicesMeta.rds = await extract(
    config.rds?.enabled === true,
    'Extracting RDS instances...',
    'RDS',
    () => extractRDSMetadata(awsCfg),
    (r) => `${r.length} instance(s)`,
  );

  servicesMeta.s3 = await extract(
    config.s3?.enabled === true,
    'Extracting S3 buckets...',
    'S3',
    () => extractS3Metadata(awsCfg),
    (r) => `${r.length} bucket(s)`,
  );

  servicesMeta.apiGateway = await extract(
    config.apiGateway?.enabled === true,
    'Extracting API Gateway routes...',
    'API Gateway',
    () => extractAPIGatewayMetadata(awsCfg),
    (r) => `${r.length} API(s), ${r.reduce((sum, api) => sum + api.routes.length, 0)} route(s)`,
  );

  servicesMeta.cognito = await extract(
    config.cognito?.enabled === true,
    'Extracting Cognito user pools...',
    'Cognito',
    () => extractCognitoMetadata(awsCfg),
    (r) => `${r.length} user pool(s)`,
  );

  const cwLogs = config.cloudwatchLogs;
  servicesMeta.logs = await extract(
    cwLogs?.enabled,
    'Sampling CloudWatch Logs (errors only, max 50 groups)...',
    'CloudWatch Logs',
    () =>
      extractLogsMetadata({
        ...awsCfg,
        logGroupPrefixes: cwLogs?.logGroupPrefixes,
        windowHours: cwLogs?.windowHours,
      }),
    (r) => `${r.length} group(s), ${r.filter((lg) => lg.errorCount > 0).length} with errors`,
  );

  // ── IaC schema (Terraform / CloudFormation / CDK) ────────────────────────────
  let iacDriftAnalyzer: IaCDriftAnalyzer | undefined;
  let iacLambdas: IaCLambda[] = [];
  let iacOutputs: IaCOutput[] = [];
  {
    const s = mkSpinner('Extracting IaC schema (Terraform / CloudFormation / CDK)...');
    try {
      const iacSchema = await extractIaCSchema(repoPath);
      const total =
        iacSchema.dynamoTables.length +
        iacSchema.rdsInstances.length +
        iacSchema.mongoClusters.length +
        iacSchema.queues.length +
        iacSchema.topics.length +
        iacSchema.lambdas.length +
        iacSchema.buckets.length +
        iacSchema.parameters.length +
        iacSchema.secrets.length +
        iacSchema.apiGateways.length +
        iacSchema.outputs.length;
      iacDriftAnalyzer = new IaCDriftAnalyzer();
      iacDriftAnalyzer.setIaCSchema(iacSchema);
      iacLambdas = iacSchema.lambdas;
      iacOutputs = iacSchema.outputs;
      s.succeed(chalk.green('IaC schema') + chalk.dim(`  ${total} resource(s) across TF/CFN/CDK`));
    } catch (err) {
      s.warn(
        chalk.yellow('IaC scan skipped') +
          chalk.dim(`  ${err instanceof Error ? err.message : String(err)}`),
      );
    }
  }

  // ── Repository scan ──────────────────────────────────────────────────────────
  let operations: ExtractedOperation[];
  {
    const s = mkSpinner(`Scanning ${path.basename(repoPath)} for service usage...`);
    try {
      operations = await scanRepository(repoPath);
      s.succeed(
        chalk.green('Repository scanned') +
          chalk.dim(`  ${operations.length} service operation(s) found`),
      );
    } catch (err) {
      s.warn(
        chalk.yellow('Repository scan failed') +
          chalk.dim(`  ${err instanceof Error ? err.message : String(err)}`),
      );
      operations = [];
    }
  }

  // ── Build graph ──────────────────────────────────────────────────────────────
  let graph: ReturnType<typeof buildGraph>;
  {
    const s = mkSpinner('Building infrastructure graph...');
    graph = buildGraph(operations, dynamoMeta, postgresMeta, mysqlMeta, mongoMeta, servicesMeta);
    addStackOutputNodes(graph, iacOutputs);
    s.succeed(
      chalk.green('Graph built') +
        chalk.dim(`  ${graph.nodes.length} nodes, ${graph.edges.length} edges`),
    );
  }

  // ── Run analyzers ────────────────────────────────────────────────────────────
  let findings: Awaited<ReturnType<typeof runAllAnalyzers>>;
  {
    const s = mkSpinner('Running analyzers...');
    const analyzers = buildAnalyzers(config, iacDriftAnalyzer, iacLambdas);
    findings = await runAllAnalyzers(graph, analyzers);
    s.succeed(chalk.green('Analysis complete') + chalk.dim(`  ${findings.length} finding(s)`));
  }

  // ── Cache ─────────────────────────────────────────────────────────────────────
  if (!options.noCache) {
    writeCache('graph', graph);
    writeCache('findings', findings);
    writeCache('operations', operations);
    writeCache('meta', {
      dynamoMeta,
      postgresMeta,
      mysqlMeta,
      mongoMeta,
      servicesMeta,
    } satisfies CachedMeta);
  }

  // ── Output ────────────────────────────────────────────────────────────────────
  if (!options.silent) {
    const displayFindings =
      minSeverity > 0
        ? findings.filter((f: Finding) => (SEVERITY_ORDER[f.severity] ?? 0) >= minSeverity)
        : findings;

    console.log('');
    if (displayFindings.length === 0) {
      const msg =
        minSeverity > 0
          ? `No ${options.severity} (or higher) severity issues found.`
          : 'Your infrastructure looks clean.';
      console.log(`  ${chalk.green.bold('✓ No issues found!')}  ${chalk.dim(msg)}`);
    } else {
      const filterNote = minSeverity > 0 ? chalk.dim(` (${options.severity}+ only)`) : '';
      console.log(
        chalk.bold(`  Findings`) + chalk.dim(`  ${displayFindings.length} total`) + filterNote,
      );
      displayFindings.forEach((f: Finding, i: number) => printFinding(f, i));
      printSummaryBox(displayFindings);
      if (displayFindings.some((f: Finding) => f.severity === 'high')) {
        console.log(
          `\n  ${chalk.red.bold('Action required:')} ${chalk.red('High severity issues detected.')}`,
        );
      }
    }

    if (options.output) {
      const report = buildMarkdownReport(displayFindings, config.project);
      const outPath = path.resolve(options.output);
      fs.writeFileSync(outPath, report, 'utf8');
      console.log('');
      log.success('Report saved', outPath);
    }

    console.log('');
    log.dim(`Results cached in .infrawise/cache/`);
    console.log('');
  }
}

export async function runCodeRefresh(
  repoPath: string,
  config: InfrawiseConfig,
): Promise<{
  graph: ReturnType<typeof buildGraph>;
  findings: Awaited<ReturnType<typeof runAllAnalyzers>>;
}> {
  const cached = readCache<CachedMeta>('meta', 60 * 60 * 1000);
  const dynamoMeta = cached?.dynamoMeta ?? [];
  const postgresMeta = cached?.postgresMeta ?? [];
  const mysqlMeta = cached?.mysqlMeta ?? [];
  const mongoMeta = cached?.mongoMeta ?? [];
  const servicesMeta = cached?.servicesMeta ?? {};

  // Re-run IaC schema (pure file scan, no AWS calls)
  let iacDriftAnalyzer: IaCDriftAnalyzer | undefined;
  let iacLambdas: IaCLambda[] = [];
  let iacOutputs: IaCOutput[] = [];
  try {
    const iacSchema = await extractIaCSchema(repoPath);
    iacDriftAnalyzer = new IaCDriftAnalyzer();
    iacDriftAnalyzer.setIaCSchema(iacSchema);
    iacLambdas = iacSchema.lambdas;
    iacOutputs = iacSchema.outputs;
  } catch {
    // IaC scan is best-effort
  }

  // Re-run repo scan
  let operations: ExtractedOperation[];
  try {
    operations = await scanRepository(repoPath);
  } catch {
    operations = [];
  }

  const graph = buildGraph(
    operations,
    dynamoMeta,
    postgresMeta,
    mysqlMeta,
    mongoMeta,
    servicesMeta,
  );
  addStackOutputNodes(graph, iacOutputs);

  const analyzers = buildAnalyzers(config, iacDriftAnalyzer, iacLambdas);
  const findings = await runAllAnalyzers(graph, analyzers);

  writeCache('graph', graph);
  writeCache('findings', findings);
  writeCache('operations', operations);

  return { graph, findings };
}
