import * as fs from 'fs';
import * as path from 'path';
import chalk from 'chalk';
import ora from 'ora';
import {
  loadConfig,
  formatError,
  writeCache,
  readCache,
  setCacheDir,
  PartialExtractionError,
} from '../../core/index.js';
import { extractDynamoMetadata } from '../../adapters/aws/dynamodb.js';
import { extractPostgresMetadata } from '../../adapters/db/postgres.js';
import { extractMySQLMetadata } from '../../adapters/db/mysql.js';
import { extractMongoMetadata } from '../../adapters/db/mongodb.js';
import {
  extractIaCSchema,
  type IaCSchema,
  type IaCLambda,
  type IaCOutput,
} from '../../adapters/iac/terraform.js';
import {
  extractSQSMetadata,
  extractSNSMetadata,
  extractSSMMetadata,
  extractSecretsMetadata,
  extractLambdaMetadata,
  extractEventBridgeMetadata,
  extractRDSMetadata,
  extractAPIGatewayMetadata,
  extractCognitoMetadata,
  extractKinesisMetadata,
  extractMSKMetadata,
  extractElastiCacheMetadata,
  extractCloudFrontMetadata,
} from '../../adapters/aws/services.js';
import { extractLogsMetadata } from '../../adapters/aws/logs.js';
import { extractRuntimeSignals } from '../../adapters/aws/metrics.js';
import { extractS3Metadata } from '../../adapters/aws/s3.js';
import { scanRepository } from '../../context/index.js';
import { buildGraph, addStackOutputNodes } from '../../graph/index.js';
import * as A from '../../analyzers/index.js';
import { printFinding, printSummaryBox, log, printHeader } from '../utils.js';
import { SEVERITY_ORDER } from '../../types.js';
import type {
  Analyzer,
  AnalysisProvenance,
  SourceStatus,
  SystemGraph,
  Finding,
  ServicesMeta,
  ExtractedOperation,
  InfrawiseConfig,
  DynamoTableMetadata,
  PostgresTableMetadata,
  MySQLTableMetadata,
  MongoCollectionMetadata,
} from '../../types.js';

interface CachedMeta {
  dynamoMeta: DynamoTableMetadata[];
  postgresMeta: PostgresTableMetadata[];
  mysqlMeta: MySQLTableMetadata[];
  mongoMeta: MongoCollectionMetadata[];
  servicesMeta: ServicesMeta;
}

interface AnalyzeOptions {
  config?: string;
  repo?: string;
  noCache?: boolean;
  output?: string;
  severity?: 'high' | 'medium' | 'low';
  silent?: boolean;
}

function buildMarkdownReport(findings: Finding[], projectName: string): string {
  const date = new Date().toISOString().split('T')[0];
  const high = findings.filter((f) => f.severity === 'high');
  const medium = findings.filter((f) => f.severity === 'medium');
  const low = findings.filter((f) => f.severity === 'low');
  const verify = findings.filter((f) => f.severity === 'verify');

  const renderGroup = (label: string, emoji: string, group: Finding[]) => {
    if (group.length === 0) return '';
    const rows = group.map((f) => `| ${f.issue} | ${f.recommendation} |`).join('\n');
    return `\n## ${emoji} ${label} (${group.length})\n\n| Issue | Recommendation |\n|---|---|\n${rows}\n`;
  };

  return [
    `# infrawise report — ${projectName}`,
    `_Generated: ${date}_`,
    '',
    `**${findings.length} finding(s)**: ${high.length} high · ${medium.length} medium · ${low.length} low · ${verify.length} verify`,
    renderGroup('High severity', '🔴', high),
    renderGroup('Medium severity', '🟡', medium),
    renderGroup('Low severity', '🟢', low),
    renderGroup('Verify (check intent)', '🔵', verify),
    '',
    '_Generated by [infrawise](https://github.com/Sidd27/infrawise) — MCP server for AWS infrastructure analysis_',
  ]
    .filter((l) => l !== undefined)
    .join('\n');
}

function mkSpinner(text: string) {
  return ora({ text: chalk.dim(text), color: 'cyan' }).start();
}

// Outcome of every extractor in the current run. Reset at the top of runAnalyze
// and persisted with the graph so the MCP layer can tell "nothing there" apart
// from "never read it".
let sourceStatuses: SourceStatus[] = [];

// Runs one extractor, printing a static completion line (never a spinner, so many
// can run concurrently without corrupting each other's output). Warns and returns
// undefined on failure so a single service never aborts the whole analysis, and
// never rejects — safe to pass straight into Promise.all. The failure is recorded
// rather than only logged: a warning on a terminal nobody read is not a signal.
async function extract<T>(
  enabled: boolean | undefined,
  service: string,
  label: string,
  fn: () => Promise<T>,
  summarize: (result: T) => string,
): Promise<T | undefined> {
  if (!enabled) {
    sourceStatuses.push({ service, status: 'disabled' });
    return undefined;
  }
  try {
    const result = await fn();
    log.success(label, summarize(result));
    sourceStatuses.push({ service, status: 'ok' });
    return result;
  } catch (err) {
    const error = err instanceof Error ? err.message : String(err);
    // Partial: the extractor kept usable data but lost a piece of it. Report the
    // gap without throwing the rest away.
    if (err instanceof PartialExtractionError) {
      const result = err.data as T;
      log.warn(`${label} incomplete`, error);
      sourceStatuses.push({ service, status: 'partial', error });
      return result;
    }
    log.warn(`${label} skipped`, error);
    sourceStatuses.push({ service, status: 'failed', error });
    return undefined;
  }
}

// Single source of truth for which analyzers run given the config. Used by both the
// full `runAnalyze` and the cache-backed `runCodeRefresh` so the two never drift.
function buildAnalyzers(
  config: InfrawiseConfig,
  iacSchema: IaCSchema | undefined,
  iacLambdas: IaCLambda[],
): Analyzer[] {
  return [
    ...(config.dynamodb?.enabled === true
      ? [
          A.FullTableScanAnalyzer,
          A.MissingGSIAnalyzer,
          (g: SystemGraph) =>
            A.HotPartitionAnalyzer(
              g,
              config.analysis?.hotPartitionThreshold,
              config.analysis?.hotPartitionThresholds,
            ),
        ]
      : []),
    ...(config.postgres?.enabled
      ? [A.MissingIndexAnalyzer, A.NplusOneAnalyzer, A.LargeSelectAnalyzer]
      : []),
    ...(config.mysql?.enabled ? [A.MissingMySQLIndexAnalyzer, A.MySQLFullTableScanAnalyzer] : []),
    ...(config.mongodb?.enabled
      ? [A.MissingMongoIndexAnalyzer, A.MongoCollectionScanAnalyzer]
      : []),
    ...(config.sqs?.enabled === true
      ? [
          A.MissingDLQAnalyzer,
          A.UnencryptedQueueAnalyzer,
          A.LargeQueueBacklogAnalyzer,
          A.VisibilityTimeoutMismatchAnalyzer,
          A.ShortRetentionNoDLQAnalyzer,
        ]
      : []),
    ...(config.secretsManager?.enabled === true ? [A.MissingSecretRotationAnalyzer] : []),
    ...(config.cloudwatchLogs?.enabled ? [A.MissingLogRetentionAnalyzer] : []),
    ...(config.lambda?.enabled === true
      ? [
          A.LambdaDefaultMemoryAnalyzer,
          A.LambdaHighTimeoutAnalyzer,
          A.LambdaMissingTriggerDLQAnalyzer,
          A.LambdaMissingIAMPermissionsAnalyzer,
          A.LambdaHighMemoryAnalyzer,
          A.MissingPartialBatchResponseAnalyzer,
          A.LambdaUnboundedConcurrencyAnalyzer,
        ]
      : []),
    ...(config.rds?.enabled === true
      ? [
          A.RDSPubliclyAccessibleAnalyzer,
          A.RDSNoBackupAnalyzer,
          A.RDSUnencryptedAnalyzer,
          A.RDSNoDeletionProtectionAnalyzer,
          A.RDSNoMultiAZAnalyzer,
          A.RDSMultiAZNonProdAnalyzer,
        ]
      : []),
    ...(config.s3?.enabled === true
      ? [A.S3PublicAccessAnalyzer, A.S3MissingVersioningAnalyzer, A.S3UnencryptedAnalyzer]
      : []),
    ...(config.elasticache?.enabled === true
      ? [A.CacheTransitEncryptionAnalyzer, A.CacheSingleNodeAnalyzer]
      : []),
    ...(config.cloudfront?.enabled === true ? [A.CloudFrontInsecureViewerProtocolAnalyzer] : []),
    ...(config.runtimeSignals?.enabled === true
      ? [A.LambdaThrottlingAnalyzer, A.StaleQueueMessagesAnalyzer]
      : []),
    ...(iacSchema ? [(g: SystemGraph) => A.IaCDriftAnalyzer(g, iacSchema)] : []),
    (g: SystemGraph) => A.PipelineAnalyzer(g, iacLambdas),
  ];
}

export async function runAnalyze(options: AnalyzeOptions = {}): Promise<void> {
  if (!options.silent) printHeader('Running Analysis');

  let config;
  try {
    config = loadConfig(options.config);
    setCacheDir(path.dirname(path.resolve(options.config ?? 'infrawise.yaml')));
    if (!options.silent) log.success('Config loaded', options.config ?? 'infrawise.yaml');
  } catch (err) {
    console.error(formatError(err));
    process.exit(1);
  }

  sourceStatuses = [];
  const repoPath = options.repo ?? process.cwd();
  const minSeverity = options.severity ? (SEVERITY_ORDER[options.severity] ?? 1) : 0;
  const awsCfg = {
    region: config.aws?.region,
    profile: config.aws?.profile,
  };

  const servicesMeta: ServicesMeta = {};

  const pgConn = config.postgres?.enabled ? config.postgres.connectionString : undefined;
  const mysqlConn = config.mysql?.enabled ? config.mysql.connectionString : undefined;
  const mongoConn = config.mongodb?.enabled ? config.mongodb.connectionString : undefined;
  const cwLogs = config.cloudwatchLogs;

  // IaC schema and the repo scan are local work (no AWS calls) — run them
  // concurrently with the AWS/DB extractors so wall-clock is bounded by the
  // slowest single task, not the sum of all of them. Each task catches its own
  // errors and never rejects, so Promise.all below can't be aborted by one.
  const iacTask = (async () => {
    if (config.terraform?.enabled === false) {
      return {
        drift: undefined as IaCSchema | undefined,
        lambdas: [] as IaCLambda[],
        outputs: [] as IaCOutput[],
      };
    }
    try {
      const iacSchema = await extractIaCSchema(repoPath);
      const total =
        iacSchema.dynamoTables.length +
        iacSchema.rdsInstances.length +
        iacSchema.mongoClusters.length +
        iacSchema.queues.length +
        iacSchema.topics.length +
        iacSchema.lambdas.length +
        iacSchema.buckets.length +
        iacSchema.parameters.length +
        iacSchema.secrets.length +
        iacSchema.apiGateways.length +
        iacSchema.outputs.length;
      log.success('IaC schema', `${total} resource(s) across TF/CFN/CDK`);
      return {
        drift: iacSchema as IaCSchema | undefined,
        lambdas: iacSchema.lambdas,
        outputs: iacSchema.outputs,
      };
    } catch (err) {
      log.warn('IaC scan skipped', err instanceof Error ? err.message : String(err));
      return {
        drift: undefined as IaCSchema | undefined,
        lambdas: [] as IaCLambda[],
        outputs: [] as IaCOutput[],
      };
    }
  })();

  const repoTask = (async () => {
    try {
      const ops = await scanRepository(repoPath);
      log.success('Repository scanned', `${ops.length} service operation(s) found`);
      return ops;
    } catch (err) {
      log.warn('Repository scan failed', err instanceof Error ? err.message : String(err));
      return [] as ExtractedOperation[];
    }
  })();

  if (!options.silent) log.info('Extracting infrastructure in parallel...');

  const [
    dynamoRes,
    postgresRes,
    mysqlRes,
    mongoRes,
    sqsRes,
    snsRes,
    ssmRes,
    secretsRes,
    lambdaRes,
    eventbridgeRes,
    rdsRes,
    s3Res,
    apiGatewayRes,
    cloudfrontRes,
    cognitoRes,
    kinesisRes,
    mskRes,
    elasticacheRes,
    logsRes,
    iac,
    operations,
  ] = await Promise.all([
    extract(
      config.dynamodb?.enabled === true,
      'dynamodb',
      'DynamoDB',
      () => extractDynamoMetadata(config),
      (r) => `${r.length} table(s)`,
    ),
    extract(
      !!pgConn,
      'postgres',
      'PostgreSQL',
      () => extractPostgresMetadata(pgConn ?? ''),
      (r) => `${r.length} table(s)`,
    ),
    extract(
      !!mysqlConn,
      'mysql',
      'MySQL',
      () => extractMySQLMetadata(mysqlConn ?? ''),
      (r) => `${r.length} table(s)`,
    ),
    extract(
      !!mongoConn,
      'mongodb',
      'MongoDB',
      () => extractMongoMetadata(mongoConn ?? '', config.mongodb?.databases),
      (r) => `${r.length} collection(s)`,
    ),
    extract(
      config.sqs?.enabled === true,
      'sqs',
      'SQS',
      () => extractSQSMetadata(awsCfg),
      (r) => `${r.length} queue(s)`,
    ),
    extract(
      config.sns?.enabled === true,
      'sns',
      'SNS',
      () => extractSNSMetadata(awsCfg),
      (r) => `${r.length} topic(s)`,
    ),
    extract(
      config.ssm?.enabled === true,
      'ssm',
      'SSM',
      () => extractSSMMetadata({ ...awsCfg, paths: config.ssm?.paths }),
      (r) => `${r.length} parameter(s)  (metadata only, no values)`,
    ),
    extract(
      config.secretsManager?.enabled === true,
      'secretsManager',
      'Secrets Manager',
      () => extractSecretsMetadata(awsCfg),
      (r) => `${r.length} secret(s)  (names/rotation only, no values)`,
    ),
    extract(
      config.lambda?.enabled === true,
      'lambda',
      'Lambda',
      () => extractLambdaMetadata(awsCfg, config.lambda?.includeFunctions),
      (r) => `${r.length} function(s)`,
    ),
    extract(
      config.eventbridge?.enabled === true,
      'eventbridge',
      'EventBridge',
      () => extractEventBridgeMetadata(awsCfg),
      (r) => `${r.length} rule(s)`,
    ),
    extract(
      config.rds?.enabled === true,
      'rds',
      'RDS',
      () => extractRDSMetadata(awsCfg),
      (r) => `${r.length} instance(s)`,
    ),
    extract(
      config.s3?.enabled === true,
      's3',
      'S3',
      () => extractS3Metadata(awsCfg),
      (r) => `${r.length} bucket(s)`,
    ),
    extract(
      config.apiGateway?.enabled === true,
      'apiGateway',
      'API Gateway',
      () => extractAPIGatewayMetadata(awsCfg),
      (r) => `${r.length} API(s), ${r.reduce((sum, api) => sum + api.routes.length, 0)} route(s)`,
    ),
    extract(
      config.cloudfront?.enabled === true,
      'cloudfront',
      'CloudFront',
      () => extractCloudFrontMetadata(awsCfg),
      (r) =>
        `${r.length} distribution(s), ${r.reduce((sum, d) => sum + d.behaviors.length, 0)} behavior(s)`,
    ),
    extract(
      config.cognito?.enabled === true,
      'cognito',
      'Cognito',
      () => extractCognitoMetadata(awsCfg),
      (r) => `${r.length} user pool(s)`,
    ),
    extract(
      config.kinesis?.enabled === true,
      'kinesis',
      'Kinesis',
      () => extractKinesisMetadata(awsCfg),
      (r) => `${r.length} stream(s)`,
    ),
    extract(
      config.msk?.enabled === true,
      'msk',
      'MSK',
      () => extractMSKMetadata(awsCfg),
      (r) => `${r.length} cluster(s)`,
    ),
    extract(
      config.elasticache?.enabled === true,
      'elasticache',
      'ElastiCache',
      () => extractElastiCacheMetadata(awsCfg),
      (r) => `${r.length} cluster(s)`,
    ),
    extract(
      cwLogs?.enabled,
      'cloudwatchLogs',
      'CloudWatch Logs',
      () =>
        extractLogsMetadata({
          ...awsCfg,
          logGroupPrefixes: cwLogs?.logGroupPrefixes,
          windowHours: cwLogs?.windowHours,
        }),
      (r) => `${r.length} group(s), ${r.filter((lg) => lg.errorCount > 0).length} with errors`,
    ),
    iacTask,
    repoTask,
  ]);

  const dynamoMeta = dynamoRes ?? [];
  const postgresMeta = postgresRes ?? [];
  const mysqlMeta = mysqlRes ?? [];
  const mongoMeta = mongoRes ?? [];
  servicesMeta.sqs = sqsRes;
  servicesMeta.sns = snsRes;
  servicesMeta.ssm = ssmRes;
  servicesMeta.secrets = secretsRes;
  servicesMeta.lambda = lambdaRes;
  servicesMeta.eventbridge = eventbridgeRes;
  servicesMeta.rds = rdsRes;
  servicesMeta.s3 = s3Res;
  servicesMeta.apiGateway = apiGatewayRes;
  servicesMeta.cloudfront = cloudfrontRes;
  servicesMeta.cognito = cognitoRes;
  servicesMeta.kinesis = kinesisRes;
  servicesMeta.msk = mskRes;
  servicesMeta.elasticache = elasticacheRes;
  servicesMeta.logs = logsRes;

  const iacDriftSchema = iac.drift;
  const iacLambdas = iac.lambdas;
  const iacOutputs = iac.outputs;

  if (config.runtimeSignals?.enabled && (servicesMeta.lambda?.length || servicesMeta.sqs?.length)) {
    const s = mkSpinner('Fetching runtime signals (CloudWatch metrics)...');
    try {
      const signals = await extractRuntimeSignals(
        awsCfg,
        (servicesMeta.lambda ?? []).map((f) => f.name),
        (servicesMeta.sqs ?? []).map((q) => q.name),
        config.runtimeSignals.windowHours,
      );
      for (const fn of servicesMeta.lambda ?? []) {
        const sig = signals.lambdas.get(fn.name);
        if (sig) {
          fn.recentThrottles = sig.throttles;
          fn.recentErrors = sig.errors;
        }
      }
      for (const q of servicesMeta.sqs ?? []) {
        const sig = signals.queues.get(q.name);
        if (sig) q.oldestMessageAgeSec = sig.oldestMessageAgeSec;
      }
      s.succeed(
        chalk.green('Runtime signals') +
          chalk.dim(`  ${signals.lambdas.size} function(s), ${signals.queues.size} queue(s)`),
      );
    } catch (err) {
      s.warn(
        chalk.yellow('Runtime signals skipped') +
          chalk.dim(`  ${err instanceof Error ? err.message : String(err)}`),
      );
    }
  }

  // ── Build graph ──────────────────────────────────────────────────────────────
  let graph: ReturnType<typeof buildGraph>;
  {
    const s = mkSpinner('Building infrastructure graph...');
    graph = buildGraph(operations, dynamoMeta, postgresMeta, mysqlMeta, mongoMeta, servicesMeta);
    addStackOutputNodes(graph, iacOutputs);
    s.succeed(
      chalk.green('Graph built') +
        chalk.dim(`  ${graph.nodes.length} nodes, ${graph.edges.length} edges`),
    );
  }

  // ── Run analyzers ────────────────────────────────────────────────────────────
  let findings: Awaited<ReturnType<typeof A.runAllAnalyzers>>;
  {
    const s = mkSpinner('Running analyzers...');
    const analyzers = buildAnalyzers(config, iacDriftSchema, iacLambdas);
    findings = await A.runAllAnalyzers(graph, analyzers);
    s.succeed(chalk.green('Analysis complete') + chalk.dim(`  ${findings.length} finding(s)`));
  }

  // ── Cache ─────────────────────────────────────────────────────────────────────
  if (!options.noCache) {
    writeCache('graph', graph);
    writeCache('findings', findings);
    writeCache('operations', operations);
    writeCache('meta', {
      dynamoMeta,
      postgresMeta,
      mysqlMeta,
      mongoMeta,
      servicesMeta,
    } satisfies CachedMeta);
    writeCache('provenance', {
      sources: sourceStatuses,
      region: config.aws?.region,
      profile: config.aws?.profile,
    } satisfies AnalysisProvenance);
  }

  // ── Output ────────────────────────────────────────────────────────────────────
  if (!options.silent) {
    const displayFindings =
      minSeverity > 0
        ? findings.filter((f: Finding) => (SEVERITY_ORDER[f.severity] ?? 0) >= minSeverity)
        : findings;

    const failed = sourceStatuses.filter((s) => s.status === 'failed');
    if (failed.length > 0) {
      console.log('');
      log.warn(
        'Incomplete analysis',
        `${failed.length} source(s) could not be read — nothing below covers them`,
      );
      for (const s of failed) log.warn(`  ${s.service}`, s.error ?? 'extraction failed');
    }

    console.log('');
    if (displayFindings.length === 0) {
      // Never claim clean when a source went unread — that is the false negative
      // the whole provenance record exists to prevent.
      const msg =
        failed.length > 0
          ? `No issues in what could be read — ${failed.length} source(s) unread, so this is not a clean bill of health.`
          : minSeverity > 0
            ? `No ${options.severity} (or higher) severity issues found.`
            : 'Your infrastructure looks clean.';
      const headline = failed.length > 0 ? '✓ No issues found' : '✓ No issues found!';
      console.log(
        `  ${(failed.length > 0 ? chalk.yellow.bold : chalk.green.bold)(headline)}  ${chalk.dim(msg)}`,
      );
    } else {
      const filterNote = minSeverity > 0 ? chalk.dim(` (${options.severity}+ only)`) : '';
      console.log(
        chalk.bold(`  Findings`) + chalk.dim(`  ${displayFindings.length} total`) + filterNote,
      );
      displayFindings.forEach((f: Finding, i: number) => printFinding(f, i));
      printSummaryBox(displayFindings);
      if (displayFindings.some((f: Finding) => f.severity === 'high')) {
        console.log(
          `\n  ${chalk.red.bold('Action required:')} ${chalk.red('High severity issues detected.')}`,
        );
      }
    }

    if (options.output) {
      const report = buildMarkdownReport(displayFindings, config.project);
      const outPath = path.resolve(options.output);
      fs.writeFileSync(outPath, report, 'utf8');
      console.log('');
      log.success('Report saved', outPath);
    }

    console.log('');
    log.dim(`Results cached in .infrawise/cache/`);
    console.log('');
  }
}

export async function runCodeRefresh(
  repoPath: string,
  config: InfrawiseConfig,
): Promise<{
  graph: ReturnType<typeof buildGraph>;
  findings: Awaited<ReturnType<typeof A.runAllAnalyzers>>;
}> {
  // Same 24h TTL as the graph cache — a shorter TTL here silently dropped all
  // AWS/DB metadata from refreshed graphs once a serve/stdio session passed 1h.
  const cached = readCache<CachedMeta>('meta', 24 * 60 * 60 * 1000);
  const dynamoMeta = cached?.dynamoMeta ?? [];
  const postgresMeta = cached?.postgresMeta ?? [];
  const mysqlMeta = cached?.mysqlMeta ?? [];
  const mongoMeta = cached?.mongoMeta ?? [];
  const servicesMeta = cached?.servicesMeta ?? {};

  // Re-run IaC schema (pure file scan, no AWS calls)
  let iacDriftSchema: IaCSchema | undefined;
  let iacLambdas: IaCLambda[] = [];
  let iacOutputs: IaCOutput[] = [];
  try {
    const iacSchema = config.terraform?.enabled === false ? null : await extractIaCSchema(repoPath);
    if (iacSchema) {
      iacDriftSchema = iacSchema;
      iacLambdas = iacSchema.lambdas;
      iacOutputs = iacSchema.outputs;
    }
  } catch {
    // IaC scan is best-effort
  }

  // Re-run repo scan
  let operations: ExtractedOperation[];
  try {
    operations = await scanRepository(repoPath);
  } catch {
    operations = [];
  }

  const graph = buildGraph(
    operations,
    dynamoMeta,
    postgresMeta,
    mysqlMeta,
    mongoMeta,
    servicesMeta,
  );
  addStackOutputNodes(graph, iacOutputs);

  const analyzers = buildAnalyzers(config, iacDriftSchema, iacLambdas);
  const findings = await A.runAllAnalyzers(graph, analyzers);

  writeCache('graph', graph);
  writeCache('findings', findings);
  writeCache('operations', operations);

  return { graph, findings };
}
