import * as fs from 'fs';
import * as path from 'path';
import chalk from 'chalk';
import ora from 'ora';
import { loadConfig, formatError, writeCache, readCache, setCacheDir } from '../../core/index.js';
import { extractDynamoMetadata } from '../../adapters/aws/dynamodb.js';
import { extractPostgresMetadata } from '../../adapters/db/postgres.js';
import { extractMySQLMetadata } from '../../adapters/db/mysql.js';
import { extractMongoMetadata } from '../../adapters/db/mongodb.js';
import { extractIaCSchema, type IaCLambda } from '../../adapters/iac/terraform.js';
import {
  extractSQSMetadata,
  extractSNSMetadata,
  extractSSMMetadata,
  extractSecretsMetadata,
  extractLambdaMetadata,
  extractEventBridgeMetadata,
  extractRDSMetadata,
} from '../../adapters/aws/services.js';
import { extractLogsMetadata } from '../../adapters/aws/logs.js';
import { extractS3Metadata } from '../../adapters/aws/s3.js';
import { scanRepository } from '../../context/index.js';
import { buildGraph } from '../../graph/index.js';
import {
  runAllAnalyzers,
  IaCDriftAnalyzer,
  PipelineAnalyzer,
  FullTableScanAnalyzer,
  MissingGSIAnalyzer,
  HotPartitionAnalyzer,
  MissingIndexAnalyzer,
  NplusOneAnalyzer,
  LargeSelectAnalyzer,
  MissingMySQLIndexAnalyzer,
  MySQLFullTableScanAnalyzer,
  MissingMongoIndexAnalyzer,
  MongoCollectionScanAnalyzer,
  MissingDLQAnalyzer,
  UnencryptedQueueAnalyzer,
  LargeQueueBacklogAnalyzer,
  MissingSecretRotationAnalyzer,
  MissingLogRetentionAnalyzer,
  LambdaDefaultMemoryAnalyzer,
  LambdaHighTimeoutAnalyzer,
  LambdaMissingTriggerDLQAnalyzer,
  RDSPubliclyAccessibleAnalyzer,
  RDSNoBackupAnalyzer,
  RDSUnencryptedAnalyzer,
  RDSNoDeletionProtectionAnalyzer,
  RDSNoMultiAZAnalyzer,
  S3PublicAccessAnalyzer,
  S3MissingVersioningAnalyzer,
  S3UnencryptedAnalyzer,
} from '../../analyzers/index.js';
import { printFinding, printSummaryBox, log, printHeader } from '../utils.js';
import type {
  Finding,
  ServicesMeta,
  ExtractedOperation,
  InfrawiseConfig,
  DynamoTableMetadata,
  PostgresTableMetadata,
  MySQLTableMetadata,
  MongoCollectionMetadata,
} from '../../types.js';

interface CachedMeta {
  dynamoMeta: DynamoTableMetadata[];
  postgresMeta: PostgresTableMetadata[];
  mysqlMeta: MySQLTableMetadata[];
  mongoMeta: MongoCollectionMetadata[];
  servicesMeta: ServicesMeta;
}

interface AnalyzeOptions {
  config?: string;
  repo?: string;
  noCache?: boolean;
  output?: string;
  severity?: 'high' | 'medium' | 'low';
  silent?: boolean;
}

const SEVERITY_ORDER: Record<string, number> = { high: 3, medium: 2, low: 1, verify: 0 };

function buildMarkdownReport(findings: Finding[], projectName: string): string {
  const date = new Date().toISOString().split('T')[0];
  const high = findings.filter((f) => f.severity === 'high');
  const medium = findings.filter((f) => f.severity === 'medium');
  const low = findings.filter((f) => f.severity === 'low');
  const verify = findings.filter((f) => f.severity === 'verify');

  const renderGroup = (label: string, emoji: string, group: Finding[]) => {
    if (group.length === 0) return '';
    const rows = group.map((f) => `| ${f.issue} | ${f.recommendation} |`).join('\n');
    return `\n## ${emoji} ${label} (${group.length})\n\n| Issue | Recommendation |\n|---|---|\n${rows}\n`;
  };

  return [
    `# infrawise report — ${projectName}`,
    `_Generated: ${date}_`,
    '',
    `**${findings.length} finding(s)**: ${high.length} high · ${medium.length} medium · ${low.length} low · ${verify.length} verify`,
    renderGroup('High severity', '🔴', high),
    renderGroup('Medium severity', '🟡', medium),
    renderGroup('Low severity', '🟢', low),
    renderGroup('Verify (check intent)', '🔵', verify),
    '',
    '_Generated by [infrawise](https://github.com/Sidd27/infrawise) — MCP server for AWS infrastructure analysis_',
  ]
    .filter((l) => l !== undefined)
    .join('\n');
}

function mkSpinner(text: string) {
  return ora({ text: chalk.dim(text), color: 'cyan' }).start();
}

export async function runAnalyze(options: AnalyzeOptions = {}): Promise<void> {
  printHeader('Running Analysis');

  let config;
  try {
    config = loadConfig(options.config);
    setCacheDir(path.dirname(path.resolve(options.config ?? 'infrawise.yaml')));
    log.success('Config loaded', options.config ?? 'infrawise.yaml');
  } catch (err) {
    console.error(formatError(err));
    process.exit(1);
  }

  const repoPath = options.repo ?? process.cwd();
  const minSeverity = options.severity ? (SEVERITY_ORDER[options.severity] ?? 1) : 0;
  const awsCfg = {
    region: config.aws?.region,
    profile: config.aws?.profile,
    endpoint: config.aws?.endpoint,
  };

  const dynamoMeta: Awaited<ReturnType<typeof extractDynamoMetadata>> = [];
  const postgresMeta: Awaited<ReturnType<typeof extractPostgresMetadata>> = [];
  const mysqlMeta: Awaited<ReturnType<typeof extractMySQLMetadata>> = [];
  const mongoMeta: Awaited<ReturnType<typeof extractMongoMetadata>> = [];
  const servicesMeta: ServicesMeta = {};

  // ── DynamoDB ────────────────────────────────────────────────────────────────
  if (config.dynamodb?.enabled === true) {
    const s = mkSpinner('Extracting DynamoDB tables...');
    try {
      const result = await extractDynamoMetadata(config);
      dynamoMeta.push(...result);
      s.succeed(chalk.green('DynamoDB') + chalk.dim(`  ${result.length} table(s)`));
    } catch (err) {
      s.warn(
        chalk.yellow('DynamoDB skipped') +
          chalk.dim(`  ${err instanceof Error ? err.message : String(err)}`),
      );
    }
  }

  // ── PostgreSQL ──────────────────────────────────────────────────────────────
  if (config.postgres?.enabled && config.postgres.connectionString) {
    const s = mkSpinner('Extracting PostgreSQL schema...');
    try {
      const result = await extractPostgresMetadata(config.postgres.connectionString);
      postgresMeta.push(...result);
      s.succeed(chalk.green('PostgreSQL') + chalk.dim(`  ${result.length} table(s)`));
    } catch (err) {
      s.warn(
        chalk.yellow('PostgreSQL skipped') +
          chalk.dim(`  ${err instanceof Error ? err.message : String(err)}`),
      );
    }
  }

  // ── MySQL ───────────────────────────────────────────────────────────────────
  if (config.mysql?.enabled && config.mysql.connectionString) {
    const s = mkSpinner('Extracting MySQL schema...');
    try {
      const result = await extractMySQLMetadata(config.mysql.connectionString);
      mysqlMeta.push(...result);
      s.succeed(chalk.green('MySQL') + chalk.dim(`  ${result.length} table(s)`));
    } catch (err) {
      s.warn(
        chalk.yellow('MySQL skipped') +
          chalk.dim(`  ${err instanceof Error ? err.message : String(err)}`),
      );
    }
  }

  // ── MongoDB ─────────────────────────────────────────────────────────────────
  if (config.mongodb?.enabled && config.mongodb.connectionString) {
    const s = mkSpinner('Extracting MongoDB schema...');
    try {
      const result = await extractMongoMetadata(
        config.mongodb.connectionString,
        config.mongodb.databases,
      );
      mongoMeta.push(...result);
      s.succeed(chalk.green('MongoDB') + chalk.dim(`  ${result.length} collection(s)`));
    } catch (err) {
      s.warn(
        chalk.yellow('MongoDB skipped') +
          chalk.dim(`  ${err instanceof Error ? err.message : String(err)}`),
      );
    }
  }

  // ── SQS ─────────────────────────────────────────────────────────────────────
  if (config.sqs?.enabled === true) {
    const s = mkSpinner('Extracting SQS queues...');
    try {
      const result = await extractSQSMetadata(awsCfg);
      servicesMeta.sqs = result;
      s.succeed(chalk.green('SQS') + chalk.dim(`  ${result.length} queue(s)`));
    } catch (err) {
      s.warn(
        chalk.yellow('SQS skipped') +
          chalk.dim(`  ${err instanceof Error ? err.message : String(err)}`),
      );
    }
  }

  // ── SNS ─────────────────────────────────────────────────────────────────────
  if (config.sns?.enabled === true) {
    const s = mkSpinner('Extracting SNS topics...');
    try {
      const result = await extractSNSMetadata(awsCfg);
      servicesMeta.sns = result;
      s.succeed(chalk.green('SNS') + chalk.dim(`  ${result.length} topic(s)`));
    } catch (err) {
      s.warn(
        chalk.yellow('SNS skipped') +
          chalk.dim(`  ${err instanceof Error ? err.message : String(err)}`),
      );
    }
  }

  // ── SSM Parameter Store ──────────────────────────────────────────────────────
  if (config.ssm?.enabled === true) {
    const s = mkSpinner('Extracting SSM parameters...');
    try {
      const result = await extractSSMMetadata({ ...awsCfg, paths: config.ssm?.paths });
      servicesMeta.ssm = result;
      s.succeed(
        chalk.green('SSM') +
          chalk.dim(`  ${result.length} parameter(s)  `) +
          chalk.dim('(metadata only, no values)'),
      );
    } catch (err) {
      s.warn(
        chalk.yellow('SSM skipped') +
          chalk.dim(`  ${err instanceof Error ? err.message : String(err)}`),
      );
    }
  }

  // ── Secrets Manager ──────────────────────────────────────────────────────────
  if (config.secretsManager?.enabled === true) {
    const s = mkSpinner('Extracting Secrets Manager metadata...');
    try {
      const result = await extractSecretsMetadata(awsCfg);
      servicesMeta.secrets = result;
      s.succeed(
        chalk.green('Secrets Manager') +
          chalk.dim(`  ${result.length} secret(s)  `) +
          chalk.dim('(names/rotation only, no values)'),
      );
    } catch (err) {
      s.warn(
        chalk.yellow('Secrets Manager skipped') +
          chalk.dim(`  ${err instanceof Error ? err.message : String(err)}`),
      );
    }
  }

  // ── Lambda ───────────────────────────────────────────────────────────────────
  if (config.lambda?.enabled === true) {
    const s = mkSpinner('Extracting Lambda functions...');
    try {
      const result = await extractLambdaMetadata(awsCfg, config.lambda?.includeFunctions);
      servicesMeta.lambda = result;
      s.succeed(chalk.green('Lambda') + chalk.dim(`  ${result.length} function(s)`));
    } catch (err) {
      s.warn(
        chalk.yellow('Lambda skipped') +
          chalk.dim(`  ${err instanceof Error ? err.message : String(err)}`),
      );
    }
  }

  // ── EventBridge ──────────────────────────────────────────────────────────────
  if (config.eventbridge?.enabled === true) {
    const s = mkSpinner('Extracting EventBridge rules...');
    try {
      const result = await extractEventBridgeMetadata(awsCfg);
      servicesMeta.eventbridge = result;
      s.succeed(chalk.green('EventBridge') + chalk.dim(`  ${result.length} rule(s)`));
    } catch (err) {
      s.warn(
        chalk.yellow('EventBridge skipped') +
          chalk.dim(`  ${err instanceof Error ? err.message : String(err)}`),
      );
    }
  }

  // ── RDS ──────────────────────────────────────────────────────────────────────
  if (config.rds?.enabled === true) {
    const s = mkSpinner('Extracting RDS instances...');
    try {
      const result = await extractRDSMetadata(awsCfg);
      servicesMeta.rds = result;
      s.succeed(chalk.green('RDS') + chalk.dim(`  ${result.length} instance(s)`));
    } catch (err) {
      s.warn(
        chalk.yellow('RDS skipped') +
          chalk.dim(`  ${err instanceof Error ? err.message : String(err)}`),
      );
    }
  }

  // ── S3 ────────────────────────────────────────────────────────────────────────
  if (config.s3?.enabled === true) {
    const s = mkSpinner('Extracting S3 buckets...');
    try {
      const result = await extractS3Metadata(awsCfg);
      servicesMeta.s3 = result;
      s.succeed(chalk.green('S3') + chalk.dim(`  ${result.length} bucket(s)`));
    } catch (err) {
      s.warn(
        chalk.yellow('S3 skipped') +
          chalk.dim(`  ${err instanceof Error ? err.message : String(err)}`),
      );
    }
  }

  // ── CloudWatch Logs ──────────────────────────────────────────────────────────
  if (config.cloudwatchLogs?.enabled) {
    const s = mkSpinner('Sampling CloudWatch Logs (errors only, max 50 groups)...');
    try {
      const result = await extractLogsMetadata({
        ...awsCfg,
        logGroupPrefixes: config.cloudwatchLogs.logGroupPrefixes,
        windowHours: config.cloudwatchLogs.windowHours,
      });
      servicesMeta.logs = result;
      const errorGroups = result.filter((lg) => lg.errorCount > 0).length;
      s.succeed(
        chalk.green('CloudWatch Logs') +
          chalk.dim(`  ${result.length} group(s), ${errorGroups} with errors`),
      );
    } catch (err) {
      s.warn(
        chalk.yellow('CloudWatch Logs skipped') +
          chalk.dim(`  ${err instanceof Error ? err.message : String(err)}`),
      );
    }
  }

  // ── IaC schema (Terraform / CloudFormation / CDK) ────────────────────────────
  let iacDriftAnalyzer: IaCDriftAnalyzer | undefined;
  let iacLambdas: IaCLambda[] = [];
  {
    const s = mkSpinner('Extracting IaC schema (Terraform / CloudFormation / CDK)...');
    try {
      const iacSchema = await extractIaCSchema(repoPath);
      const total =
        iacSchema.dynamoTables.length +
        iacSchema.rdsInstances.length +
        iacSchema.mongoClusters.length +
        iacSchema.queues.length +
        iacSchema.topics.length +
        iacSchema.lambdas.length +
        iacSchema.buckets.length +
        iacSchema.parameters.length +
        iacSchema.secrets.length +
        iacSchema.apiGateways.length;
      iacDriftAnalyzer = new IaCDriftAnalyzer();
      iacDriftAnalyzer.setIaCSchema(iacSchema);
      iacLambdas = iacSchema.lambdas;
      s.succeed(chalk.green('IaC schema') + chalk.dim(`  ${total} resource(s) across TF/CFN/CDK`));
    } catch (err) {
      s.warn(
        chalk.yellow('IaC scan skipped') +
          chalk.dim(`  ${err instanceof Error ? err.message : String(err)}`),
      );
    }
  }

  // ── Repository scan ──────────────────────────────────────────────────────────
  let operations: ExtractedOperation[];
  {
    const s = mkSpinner(`Scanning ${path.basename(repoPath)} for service usage...`);
    try {
      operations = await scanRepository(repoPath);
      s.succeed(
        chalk.green('Repository scanned') +
          chalk.dim(`  ${operations.length} service operation(s) found`),
      );
    } catch (err) {
      s.warn(
        chalk.yellow('Repository scan failed') +
          chalk.dim(`  ${err instanceof Error ? err.message : String(err)}`),
      );
      operations = [];
    }
  }

  // ── Build graph ──────────────────────────────────────────────────────────────
  let graph: ReturnType<typeof buildGraph>;
  {
    const s = mkSpinner('Building infrastructure graph...');
    graph = buildGraph(operations, dynamoMeta, postgresMeta, mysqlMeta, mongoMeta, servicesMeta);
    s.succeed(
      chalk.green('Graph built') +
        chalk.dim(`  ${graph.nodes.length} nodes, ${graph.edges.length} edges`),
    );
  }

  // ── Run analyzers ────────────────────────────────────────────────────────────
  let findings: Awaited<ReturnType<typeof runAllAnalyzers>>;
  {
    const s = mkSpinner('Running analyzers...');
    const hotPartitionThreshold = config.analysis?.hotPartitionThreshold;
    const hotPartitionThresholds = config.analysis?.hotPartitionThresholds;
    const pipelineAnalyzer = new PipelineAnalyzer();
    pipelineAnalyzer.setIaCLambdas(iacLambdas);
    const analyzers = [
      ...(config.dynamodb?.enabled === true
        ? [
            new FullTableScanAnalyzer(),
            new MissingGSIAnalyzer(),
            new HotPartitionAnalyzer(hotPartitionThreshold, hotPartitionThresholds),
          ]
        : []),
      ...(config.postgres?.enabled
        ? [new MissingIndexAnalyzer(), new NplusOneAnalyzer(), new LargeSelectAnalyzer()]
        : []),
      ...(config.mysql?.enabled
        ? [new MissingMySQLIndexAnalyzer(), new MySQLFullTableScanAnalyzer()]
        : []),
      ...(config.mongodb?.enabled
        ? [new MissingMongoIndexAnalyzer(), new MongoCollectionScanAnalyzer()]
        : []),
      ...(config.sqs?.enabled === true
        ? [
            new MissingDLQAnalyzer(),
            new UnencryptedQueueAnalyzer(),
            new LargeQueueBacklogAnalyzer(),
          ]
        : []),
      ...(config.secretsManager?.enabled === true ? [new MissingSecretRotationAnalyzer()] : []),
      ...(config.cloudwatchLogs?.enabled ? [new MissingLogRetentionAnalyzer()] : []),
      ...(config.lambda?.enabled === true
        ? [
            new LambdaDefaultMemoryAnalyzer(),
            new LambdaHighTimeoutAnalyzer(),
            new LambdaMissingTriggerDLQAnalyzer(),
          ]
        : []),
      ...(config.rds?.enabled === true
        ? [
            new RDSPubliclyAccessibleAnalyzer(),
            new RDSNoBackupAnalyzer(),
            new RDSUnencryptedAnalyzer(),
            new RDSNoDeletionProtectionAnalyzer(),
            new RDSNoMultiAZAnalyzer(),
          ]
        : []),
      ...(config.s3?.enabled === true
        ? [
            new S3PublicAccessAnalyzer(),
            new S3MissingVersioningAnalyzer(),
            new S3UnencryptedAnalyzer(),
          ]
        : []),
      ...(iacDriftAnalyzer ? [iacDriftAnalyzer] : []),
      pipelineAnalyzer,
    ];
    findings = await runAllAnalyzers(graph, analyzers);
    s.succeed(chalk.green('Analysis complete') + chalk.dim(`  ${findings.length} finding(s)`));
  }

  // ── Cache ─────────────────────────────────────────────────────────────────────
  if (!options.noCache) {
    writeCache('graph', graph);
    writeCache('findings', findings);
    writeCache('operations', operations);
    writeCache('meta', {
      dynamoMeta,
      postgresMeta,
      mysqlMeta,
      mongoMeta,
      servicesMeta,
    } satisfies CachedMeta);
  }

  // ── Output ────────────────────────────────────────────────────────────────────
  if (!options.silent) {
    const displayFindings =
      minSeverity > 0
        ? findings.filter((f: Finding) => (SEVERITY_ORDER[f.severity] ?? 0) >= minSeverity)
        : findings;

    console.log('');
    if (displayFindings.length === 0) {
      const msg =
        minSeverity > 0
          ? `No ${options.severity} (or higher) severity issues found.`
          : 'Your infrastructure looks clean.';
      console.log(`  ${chalk.green.bold('✓ No issues found!')}  ${chalk.dim(msg)}`);
    } else {
      const filterNote = minSeverity > 0 ? chalk.dim(` (${options.severity}+ only)`) : '';
      console.log(
        chalk.bold(`  Findings`) + chalk.dim(`  ${displayFindings.length} total`) + filterNote,
      );
      displayFindings.forEach((f: Finding, i: number) => printFinding(f, i));
      printSummaryBox(displayFindings);
      if (displayFindings.some((f: Finding) => f.severity === 'high')) {
        console.log(
          `\n  ${chalk.red.bold('Action required:')} ${chalk.red('High severity issues detected.')}`,
        );
      }
    }

    if (options.output) {
      const report = buildMarkdownReport(displayFindings, config.project);
      const outPath = path.resolve(options.output);
      fs.writeFileSync(outPath, report, 'utf8');
      console.log('');
      log.success('Report saved', outPath);
    }

    console.log('');
    log.dim(`Results cached in .infrawise/cache/`);
    console.log('');
  }
}

export async function runCodeRefresh(
  repoPath: string,
  config: InfrawiseConfig,
): Promise<{
  graph: ReturnType<typeof buildGraph>;
  findings: Awaited<ReturnType<typeof runAllAnalyzers>>;
}> {
  const cached = readCache<CachedMeta>('meta', 60 * 60 * 1000);
  const dynamoMeta = cached?.dynamoMeta ?? [];
  const postgresMeta = cached?.postgresMeta ?? [];
  const mysqlMeta = cached?.mysqlMeta ?? [];
  const mongoMeta = cached?.mongoMeta ?? [];
  const servicesMeta = cached?.servicesMeta ?? {};

  // Re-run IaC schema (pure file scan, no AWS calls)
  let iacDriftAnalyzer: IaCDriftAnalyzer | undefined;
  let iacLambdas: IaCLambda[] = [];
  try {
    const iacSchema = await extractIaCSchema(repoPath);
    iacDriftAnalyzer = new IaCDriftAnalyzer();
    iacDriftAnalyzer.setIaCSchema(iacSchema);
    iacLambdas = iacSchema.lambdas;
  } catch {
    // IaC scan is best-effort
  }

  // Re-run repo scan
  let operations: ExtractedOperation[];
  try {
    operations = await scanRepository(repoPath);
  } catch {
    operations = [];
  }

  const graph = buildGraph(
    operations,
    dynamoMeta,
    postgresMeta,
    mysqlMeta,
    mongoMeta,
    servicesMeta,
  );

  const hotPartitionThreshold = config.analysis?.hotPartitionThreshold;
  const hotPartitionThresholds = config.analysis?.hotPartitionThresholds;
  const pipelineAnalyzer = new PipelineAnalyzer();
  pipelineAnalyzer.setIaCLambdas(iacLambdas);
  const analyzers = [
    ...(config.dynamodb?.enabled === true
      ? [
          new FullTableScanAnalyzer(),
          new MissingGSIAnalyzer(),
          new HotPartitionAnalyzer(hotPartitionThreshold, hotPartitionThresholds),
        ]
      : []),
    ...(config.postgres?.enabled
      ? [new MissingIndexAnalyzer(), new NplusOneAnalyzer(), new LargeSelectAnalyzer()]
      : []),
    ...(config.mysql?.enabled
      ? [new MissingMySQLIndexAnalyzer(), new MySQLFullTableScanAnalyzer()]
      : []),
    ...(config.mongodb?.enabled
      ? [new MissingMongoIndexAnalyzer(), new MongoCollectionScanAnalyzer()]
      : []),
    ...(config.sqs?.enabled === true
      ? [new MissingDLQAnalyzer(), new UnencryptedQueueAnalyzer(), new LargeQueueBacklogAnalyzer()]
      : []),
    ...(config.secretsManager?.enabled === true ? [new MissingSecretRotationAnalyzer()] : []),
    ...(config.cloudwatchLogs?.enabled ? [new MissingLogRetentionAnalyzer()] : []),
    ...(config.lambda?.enabled === true
      ? [
          new LambdaDefaultMemoryAnalyzer(),
          new LambdaHighTimeoutAnalyzer(),
          new LambdaMissingTriggerDLQAnalyzer(),
        ]
      : []),
    ...(config.rds?.enabled === true
      ? [
          new RDSPubliclyAccessibleAnalyzer(),
          new RDSNoBackupAnalyzer(),
          new RDSUnencryptedAnalyzer(),
          new RDSNoDeletionProtectionAnalyzer(),
          new RDSNoMultiAZAnalyzer(),
        ]
      : []),
    ...(config.s3?.enabled === true
      ? [
          new S3PublicAccessAnalyzer(),
          new S3MissingVersioningAnalyzer(),
          new S3UnencryptedAnalyzer(),
        ]
      : []),
    ...(iacDriftAnalyzer ? [iacDriftAnalyzer] : []),
    pipelineAnalyzer,
  ];

  const findings = await runAllAnalyzers(graph, analyzers);

  writeCache('graph', graph);
  writeCache('findings', findings);
  writeCache('operations', operations);

  return { graph, findings };
}
